name: documentation

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install -r docs/doc_requirements.txt

      - name: Generate Doxygen Documentation
        run: |
          sudo apt install -y doxygen
          mkdir -p docs/build/doxygen
          doxygen docs/Doxyfile
      
      - name: Sphinx build
        run: |
          sphinx-build  docs/ docs/build/html

      - name: Move to versioned directory
        run: |
          mkdir -p .github/pages
          mv docs/build/html .github/pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/pages
          force_orphan: true