name: Docs CI
on: 
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Install Doxygen
        run: sudo apt install -y doxygen graphviz
        shell: bash

      - name: Generate Doxygen Documentation
        run: docs/doxygen.sh
        shell: bash

      - name: Build Docs
        run: pip install ./python[dev] && sphinx-build -ET docs/ docs/build/html/

      - name: Sanitize ref name for docs version
        run: echo "DOCS_VERSION=${GITHUB_REF_NAME//[^A-Za-z0-9._-]/_}" >> $GITHUB_ENV

      - name: Move to versioned directory
        run: mv docs/build/html .github/pages/$DOCS_VERSION
